openapi: 3.0.3
info:
  title: Digi-Mart Service - OpenAPI 3.0
  description: |-
    Digi Mart Service API Spec
  version: 0.0.1
  contact:
    name: API Support
    email: work.mitakshar@gmail.com
servers:
  - url: api
tags:
  - name: user mgmt v1
    description: User management endpoints version 1
paths:
  #**************************************User MGMT******************************************************
  /v1/auth/signup:
    post:
      tags:
        - auth controller v1
      summary: Sign-Up/Register
      description: Sign up/Register New User
      operationId: signUp
      requestBody:
        description: Sign Up Request
        content:
          application/json:
            schema:
              $ref: './UserMgmtApiComponents.yaml#/components/schemas/SignUpRequest'
        required: true
      responses:
        '201':
          description: "Sign Up Success"
          content:
            application/json:
              schema:
                $ref: './UserMgmtApiComponents.yaml#/components/schemas/AuthResponse'
        '422':
          description: "Signup Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './UserMgmtApiComponents.yaml#/components/schemas/UserMgmtBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './UserMgmtApiComponents.yaml#/components/schemas/UserMgmtBaseApiResponse'

  /v1/auth/signin:
    post:
      tags:
        - auth controller v1
      summary: Sign-In
      description: Sign-In
      operationId: signIn
      requestBody:
        description: Sign In Request
        content:
          application/json:
            schema:
              $ref: './UserMgmtApiComponents.yaml#/components/schemas/SignInRequest'
        required: true
      responses:
        '200':
          description: "Sign In Success"
          content:
            application/json:
              schema:
                $ref: './UserMgmtApiComponents.yaml#/components/schemas/AuthResponse'
        '422':
          description: "Signup Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './UserMgmtApiComponents.yaml#/components/schemas/UserMgmtBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './UserMgmtApiComponents.yaml#/components/schemas/UserMgmtBaseApiResponse'

  /v1/auth/activate:
    post:
      tags:
        - auth controller v1
      summary: Activate User
      description: Activate User
      operationId: activateUser
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        description: Activation Request
        content:
          application/json:
            schema:
              $ref: './UserMgmtApiComponents.yaml#/components/schemas/ActivationRequest'
        required: true
      responses:
        '200':
          description: "Account Activated Successfully"
          content:
            application/json:
              schema:
                $ref: './UserMgmtApiComponents.yaml#/components/schemas/ActivationResponse'
        '422':
          description: "Activation Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './UserMgmtApiComponents.yaml#/components/schemas/UserMgmtBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './UserMgmtApiComponents.yaml#/components/schemas/UserMgmtBaseApiResponse'

  /v1/auth/generateCode:
    post:
      tags:
        - auth controller v1
      summary: Generate User Activation Code
      description: Generate User Activation Code
      operationId: regenerateActivationCode
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        '200':
          description: "Activation Code Sent Successfully"
          content:
            application/json:
              schema:
                $ref: './UserMgmtApiComponents.yaml#/components/schemas/UserMgmtBaseApiResponse'
        '422':
          description: "Activation Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './UserMgmtApiComponents.yaml#/components/schemas/UserMgmtBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './UserMgmtApiComponents.yaml#/components/schemas/UserMgmtBaseApiResponse'